version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8686:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin@123456
      - POSTGRES_DB=autologin
  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin4_container
      restart: always
      ports:
        - "5050:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin@123456
      volumes:
        - pgadmin-data:/var/lib/pgadmin
  # selenium-hub:
  #     image: selenium/hub:4.1.4-20220427
  #     container_name: selenium-hub
  #     ports:
  #       - "4442:4442"
  #       - "4443:4443"
  #       - "4444:4444"
  # chrome:
  #     image: selenium/node-chrome:4.1.4-20220427
  #     shm_size: 2gb
  #     depends_on:
  #       - selenium-hub
  #     environment:
  #       - SE_EVENT_BUS_HOST=selenium-hub
  #       - SE_EVENT_BUS_PUBLISH_PORT=4442
  #       - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
volumes:
  postgres_data:
  pgadmin-data: