# Generated by Django 4.1.4 on 2022-12-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='website_credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('website_type', models.IntegerField()),
            ],
        ),
    ]
